### ISSUE TITLE
Cannot build project after updating MySql.Data to 6.10.5

### ISSUE THREAD

**Issue by HSyr** [MySqlBackupNET/MySqlBackup.Net#10]

**Comment by adriancs2** [comment]
Current release of MySqlBackup.NET is build for MySql.Data 6.9.10.
Looks like I'm gonna repack it for 6.10.5.

I've contacted the developer team of Connector/NET. Hopefully, MySqlBackup.NET will be integrated into MySql.Data one day :)

**Comment by adriancs2** [comment]
Their source code for 6.10.5 is not released yet, thus I can't compile for .NET 2.0 and .NET 4.6.1.
How about you manually include the source code of MySqlBackup.NET into your project directly.
This will fix a lots dependencies headache.

**Comment by adriancs2** [comment]
If you are coding in VB.NET, you can try to recompile MySqlBackup.NET with your desire version of MySql.Data.
