### ISSUE TITLE
When server does not support column-statistics

### ISSUE THREAD

**Issue by iamsagarmaheta** [MySqlBackupNET/MySqlBackup.Net#107]
since last few days I've been getting the following error : 

"Couldn't execute 'SELECT COLUMN_NAME, JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"') FROM information_schema.COLUMN_STATISTICS WHERE SCHEMA_NAME="

**Comment by adriancs2** [comment]
You can use this:
```
// this might take some/lots of time
mb.ExportInfo.GetTotalRowsMode = GetTotalRowsMethod.SelectCount;
or
// this might save some/lots of time
mb.ExportInfo.GetTotalRowsMode = Skip;

// depands on how many rows do you have in your database
```

**Comment by iamsagarmaheta** [comment]
thanks for help
i tried this 
although i am getting another error so i think this is working 
so closing the issue for now
