### ISSUE TITLE
How to disable column-statistics ? on shared server ?

### ISSUE THREAD

**Issue by iamsagarmaheta** [MySqlBackupNET/MySqlBackup.Net#108]
i've been using shared hostinger servers which provides mysql database 
since it is not VPN i can not disable column-statistic 
and when i try to take backup i am getting error cause server does not support column-statistics
so is there any way to disable it ?
i am unable to take backup

**Comment by adriancs2** [comment]
You can use this:
```
// this might take some/lots of time
mb.ExportInfo.GetTotalRowsMode = GetTotalRowsMethod.SelectCount;
or
// this might save some/lots of time
mb.ExportInfo.GetTotalRowsMode = Skip;

// depands on how many rows do you have in your database
```

**Comment by iamsagarmaheta** [comment]
thanks for help
i tried this 
although i am getting another error so i think this is working 
so closing the issue for now
