### ISSUE TITLE
Problem With Double Quotes

### ISSUE THREAD

**Issue by ChecheSwap** [MySqlBackupNET/MySqlBackup.Net#11]
I have a problem when I export a database using this tool, the name of the table is in double quotes when is in the create statment, the right form is only in simple quotes, can anyone help me?
![sin titulo](https://user-images.githubusercontent.com/21239660/34452475-b90fa590-ecfd-11e7-882b-8ae85103505f.png)

**Comment by adriancs2** [comment]
Hi, this has nothing to do with MySqlBackup.NET
It is the behavior of MySql Server which can be configured either as default (GLOBAL) behavior or temporary (SESSION) behavior of MySQL server.

Here is the SQL statements that you can try out yourself:

Example 1: Export table structure with double quotes:

```
set session sql_mode=ANSI_QUOTES;
show create table `configkey`;
```
output:
```
CREATE TABLE "configkey" (
  "key" varchar(100) NOT NULL,
  "value" text,
  PRIMARY KEY ("key")
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
Example 2: Export table structure with single quote
```
set session sql_mode=traditional;
show create table `configkey`;
```
output:
```
CREATE TABLE `configkey` (
  `key` varchar(100) NOT NULL,
  `value` text,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
For more information, please refer to official MySQL documentation under the topic: **SQL-MODE**
https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_sql-mode
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html

**Comment by ChecheSwap** [comment]
Thank you very much.
