### ISSUE TITLE
Exception when trying to back up tables with more than 2GB

### ISSUE THREAD

**Issue by adrbarros** [MySqlBackupNET/MySqlBackup.Net#110]
Hello.

I have a database running since 2008, some tables are very large, between 2 to 4.5 GB and the total database has 19GB, is currently in a Server Linux Centos 8 32GB RAM, the MySQL versions have been evolving and being migrated with Over the years, starting in version 5.1 and currently in version 8.

Using the library, when backing up the database, when it starts backing up the larger tables occurs Timeout errors, it is not always in the same table. I've increased the timeout and yet persists in these mistakes.

Does anyone have any tips, not to happen this kind of exception when performing the backup using the library?

Note: Backup via command line, it works perfectly. 
Example of the command used via command line:
mysqldump -u USET -pPASS DATABASE - -adddrop -database - -adddrop -table -x -a -e -k -r -b> directory\backup_database_yyymddhmmm.sql

**Comment by adriancs2** [comment]
Have you tried the connection string option of `ConnectionTimeout`
```
Server=yourserver;Database=yourdatabase;User ID=youruserid;Password=yourpassword;ConnectionTimeout=60;
```

**Comment by adriancs2** [comment]
Where did you execute mysqldump and mysqlbackup.net? 
Were they run on the same machine as the MySQL server?

**Comment by adrbarros** [comment]
Backup or executed with MySQLBackup.net, I already set up the Timeout on the connection string, and using MySQLBackup.net happens the exception (error when backing on tables with over 2GB)

Scenario:
MySQL server is a centos 8 with 32GB RAM

Backup application is on a Windows 2019 server, developed in .net Windows Forms

**Comment by adrbarros** [comment]
The Connection Timeout I already define at 60, 6000, 60000, 600000
My application is performed in backgroud, but always generates the same error.

Now I tested with the test solution that is in Github, and also the same error.

![image](https://github.com/MySqlBackupNET/MySqlBackup.Net/assets/15065213/5c1b9bfb-75b8-4e72-bd71-a7b14a6e868d)

**Comment by adriancs2** [comment]
I see, can you try again with MySqlConnector instead:
https://www.nuget.org/packages/MySqlBackup.NET.MySqlConnector/

you can write a simple small app just for this testing

**Comment by adriancs2** [comment]
If you using the demo test app from github, you may use the function of "Progress Report - Export":

This function is run by using Background Worker, which runs MySqlBackup.net in a separate thread.

![MySqlBackup Test App - Progress Report Export](https://github.com/MySqlBackupNET/MySqlBackup.Net/assets/646615/cccf2b5a-bf6c-4d4a-8f4e-c5e009284d8e)

**Comment by adrbarros** [comment]
Using the 2 (mysql.data or mysqlconnector) connectors, it fires the same exception.

I will perform other tests, because with mysqlconnector the exception occurred in the last table that contains a lot of data, in this case I think increasing the timeout can resolve

Thank you for your help.

![image](https://github.com/MySqlBackupNET/MySqlBackup.Net/assets/15065213/efdc2341-217e-4e40-97c5-0bce4c22842c)
