### ISSUE TITLE
Datetime Convert Error.

### ISSUE THREAD

**Issue by yhackup** [MySqlBackupNET/MySqlBackup.Net#111]
I get Datetime error.

![image](https://github.com/MySqlBackupNET/MySqlBackup.Net/assets/15657038/19f6d476-b470-46ed-98dc-72cb5bbcf1bd)

**Comment by adriancs2** [comment]
add `allowzerodatetime=true` into your connection options, for more information please refer:

https://github.com/MySqlBackupNET/MySqlBackup.Net/wiki/Frequently-Asked-Questions-(FAQ)---Commonly-Seen-Error#2-mysqldatatypesmysqlconversionexception-unable-to-convert-mysql-datetime-value-to-systemdatetime
