### ISSUE TITLE
Stored Procedures - DROP command problem on Stored Procedures

### ISSUE THREAD

**Issue by jxburns** [MySqlBackupNET/MySqlBackup.Net#12]
Great bit of code which saved me a lot of effort with mysqldump etc. 

If the DEFINER user in the Stored Procedures is not the same as the database connection user all that happens when a table is dumped, with ".ExportProcedures" set to TRUE, is that the sql file generated contains a series of DROP commands (see below). This of course could be a major problem if the developer does not realise it will delete all the stored procedures in the destination database. So may need a change that if there is a user conflict that the DROP procedure is not generated to avoid undesired deletions from the destination database.

DROP PROCEDURE IF EXISTS `queryname`;
DELIMITER |
 |
DELIMITER ;

Thanks - John

**Comment by adriancs2** [comment]
How about set 
```
ExportInfo.ExportRoutinesWithoutDefiner = true;
```
Does this solve your problem?

**Comment by jxburns** [comment]
No. Sorry. It made no difference although I did not have this in the code initially primarily as had not seen it as a property nor found mention of it in any docs either on GitHub or CodePlex.

What is it designed to do?

The only way I have found to export the procedures is to make sure the user in the Definer matches the user in the connection string.

Thanks - John

**Comment by adriancs2** [comment]
It exports the procedure without definer.

**Comment by jxburns** [comment]
OK but still generates a simple DROP procedure without any CREATE contents if the user names do not match. Matching the user names works perfectly even though both have full permissions to the DB.

**Comment by adriancs2** [comment]
What do you suggest on solution on this matter?
Are you trying to suggest to remove the "DROP"?

**Comment by jxburns** [comment]
I'm not sure whether your code is even comparing the procedure definer name versus the connection user name. My only concern is that if they are different the system is generating a drop command for the procedure without a corresponding create command and thus deleting the destination procedures. If there is a way to compare the two, and then add a property (perhaps) that allows the end user to decide whether to create the drop only command then would be perfect e.g. "NoDropIfDefinerDifferent".

It is such a useful bit of code that this is just a minor nice to have rather than a bug or "feature".

Thanks - John

**Comment by adriancs2** [comment]
I'm actually not aware of this problem will occur. After doing some testing, googling, below are some of my findings:

The definer is a combination of "username" and "host". Example:
```
john@localhost or
john@% or
john@102.291.9.54
```
Combination is in a variety of format and possibilities. It would take some efforts to manually compare all the possibilities.

But I found a better solution which is by identifying the create command of the `CREATE PROCEDURE`.

I'm using the following to get a list of stored procedure:
```
SHOW PROCEDURE STATUS;
```
Then, I use this to get the original create command for specific procedure:
```
SHOW CREATE PROCEDURE `sampleProcedure1`
```
The create command will be empty/hidden for a few circumstances:
1st Check: The `SQL Security` mode of the procedure
2nd Check: The definer
3rd Check: The user privilege

So, in stead of comparing the definer, we can directly identify the create command.

Is it "empty" or not.

If the create command is empty >> skip and remove "DROP".

If the create command is not empty >> proceed with "DROP" and append the "CREATE" command below.

I have done some googling and found the following info, you can have a look.
https://dev.mysql.com/doc/refman/5.7/en/stored-programs-security.html

I will release an update of this fix later.
Thanks for your effort and time on reporting this problem :)

**Comment by adriancs2** [comment]
Ah.... the new source code of MySql.Data from Oracle is not in .NET Framework format.
Need manual work to convert it into .NET Framework to support 2.0.

**Comment by adriancs2** [comment]
I have a problem to reference the latest release of MySql.Data source code into MySqlBackup.NET project. The latest also seems not to be compatible with .NET Framework 2.0. I did not apply MySql.Data 6.10.5 at the moment.

I have released the fix, you can try it out at https://github.com/MySqlBackupNET/MySqlBackup.Net/tree/master/Precompiled%20Binaries/2.0.11

**Comment by jxburns** [comment]
Thanks for the work on this and I understand what you have had to do. If I understand you right this is for .NET 2.0? I did not make clear I am currently using .NET 4.x (specifically 4.6.1) so wonder if you have a version for that framework? Thanks - John

**Comment by adriancs2** [comment]
Ok done, you can download now.

**Comment by jxburns** [comment]
Think you may have uploaded the wrong version of MYSQLBACKUP.DLL? It is showing as 2.0.10 (instead of .11) in https://github.com/MySqlBackupNET/MySqlBackup.Net/tree/master/Precompiled%20Binaries/2.0.11/v4.6.1

**Comment by adriancs2** [comment]
The content is actually 2.0.11, but I have forgotten to update the file version info. Ok, updated now, you can try again.

**Comment by jxburns** [comment]
OK now showing as 2.0.11 but now getting a "Strong name validation failed." error. I have checked that only the 2 DLL files from the repository are now being referenced and removed all the NuGet imports that I was using.

**Comment by adriancs2** [comment]
There are too many versions of MySql.Data.DLL. Try remove the version of MySql.Data.DLL too and reference the version with MySqlBackup.NET in the repository

**Comment by jxburns** [comment]
I had already removed all references to any other versions of MySql.Data.DLL from the repository and am using the 2 x files from GitHub. So version 2.0.11 of MySqlBackup and 6.9.10 of MySql.Data. Those same version files are in the output folder after compilation. This is happening when the source database connection is being opened.

If I revert to 2.0.10 versions of the 2 files, system works fine (other than the DROP command of course).

John

**Comment by adriancs2** [comment]
Ok, I have recompiled the binaries without public key signing.
You may try again.
https://github.com/MySqlBackupNET/MySqlBackup.Net/tree/master/Precompiled%20Binaries/2.0.11

**Comment by jxburns** [comment]
This is perfect. Fully tested.

With definer=db username:
With ExportRoutinesWithoutDefiner = False then procedures exported with the original definer name.
With ExportRoutinesWithoutDefiner = True then procedures exported with no definer name.

With definer <>db username:
No procedures exported regardless of what ExportRoutinesWithoutDefiner set to and no DROP clause either.

Many thanks - John

**Comment by adriancs2** [comment]
You're welcome
