### ISSUE TITLE
MySql.Data Version

### ISSUE THREAD

**Issue by DCarty** [MySqlBackupNET/MySqlBackup.Net#14]
Is this still being maintained? MySql.Data Version v6.10.6.  Outdated on Nuget.  Great package though.

**Comment by adriancs2** [comment]
Hi, NuGet Package updated to MySql.Data v6.10.6.
but only for the following target framework v.4.6.1 and v.4.5.2.
you may review the MySql.Data version below:

MySql.Data Version
-----------------------
.NET 2.0 = 6.9.10 (Recompiled)
.NET 4.0 = 6.10.5 (Recompiled)
.NET 4.5 = 6.10.5 (Recompiled)
.NET 4.5.2 = 6.10.6 (Official)
.NET 4.6.1 = 6.10.6 (Official)

**Comment by DCarty** [comment]
Fab, really appreciate your fast response.  Love this package.

**Comment by adriancs2** [comment]
You're welcome.
