### ISSUE TITLE
using Devart.data unstead of MySql.data

### ISSUE THREAD

**Issue by cobra23** [MySqlBackupNET/MySqlBackup.Net#16]
Dear adriancs2,
Thank you for this very helpfull project, Can i use Devart.data.dll unstead of Mysql.data.dll and how? because Mysql.data.dll is a GPL licensed
Kind Regard
Mohammed

**Comment by adriancs2** [comment]
MySqlBackup.NET uses a component (MySqlCommand) from MySql.Data.DLL. MySql.Data.DLL must be reference. But however, you can easily replace MySql.Data.DLL with Devart.Data.DLL.

What you need to do is replace the following variables of the whole project of MySql.Data.DLL with the equivalent components in Devart.Data.DLL.

**Comment by cobra23** [comment]
Thank you for the response, but i did that, and it shows me an error on MySqlScript don't exist and MySqlTokenizer too,( i am using devart mysql connector express)

**Comment by adriancs2** [comment]
Hi cobra23, I have made another version of MySqlBackup.NET with minor modification to meet the class components of Devart Express Connector.

You can download the DLL at release section of this project: https://github.com/MySqlBackupNET/MySqlBackup.Net/releases

**Comment by adriancs2** [comment]
MySqlBackupNET now supports Devart.Data.MySQL

**Comment by cobra23** [comment]
Thank you very much for the code
