### ISSUE TITLE
Export with double quotes issue

### ISSUE THREAD

**Issue by xiaoma88** [MySqlBackupNET/MySqlBackup.Net#19]
Hi, thanks for your DLL that helped me alot.
Everything worked fine (Export and import without any issue) 
But when I tried to insert any data to my table and export it, some of the backtick replaced with double quotes, example:

DROP TABLE IF EXISTS `TestTable`;
CREATE TABLE IF NOT EXISTS "TestTable" (
  "ID" int(11) NOT NULL AUTO_INCREMENT,
  "WW" int(6) NOT NULL,
  "Date" varchar(30) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  "UserID" varchar(40) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  "Amount" decimal(19,2) NOT NULL,

"These "TestTable", "ID", "WW" should come with backquote.
And restoring this backup.sql will give me error and drop all my table.
Hope I can understand why it happens?

Thanks for your hardworking!

**Comment by adriancs2** [comment]
You can have read on this issue: https://github.com/MySqlBackupNET/MySqlBackup.Net/issues/11

It explains the solutions.
