### ISSUE TITLE
Make backups daily / weekly / monthly.

### ISSUE THREAD

**Issue by tiagossa1** [MySqlBackupNET/MySqlBackup.Net#20]
Hey,
not really a issue, but I'm looking forward to know if there's any possibility of programming my program to make backups whenever the user wants, like daily or weekly, for example.

Here's my program: https://ghostbin.com/paste/j2ofh
It does nothing spetacular, just creates a dump file.
thanks.

**Comment by adriancs2** [comment]
You can create a Windows Schedule Task or write a program with a timer to execute the backup task daily or weekly.

**Comment by tiagossa1** [comment]
Thank you! :)

**Comment by adriancs2** [comment]
You're welcome
