### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by sridhargoshika** [MySqlBackupNET/MySqlBackup.Net#22]
I am getting out of memory exception when calling function ExportToMemoryStream(ms) for large database?

Here is my code, 

    GC.Collect();
    using (MySqlConnection con = new MySqlConnection(conBuilder.ToString()))
    {
     using (MySqlCommand cmd = new MySqlCommand())
      {
       using (MySqlBackup mb = new MySqlBackup(cmd))
        {
         mb.ExportInfo.AddCreateDatabase = False;
         mb.ExportInfo.ExportTableStructure = True;
         mb.ExportInfo.ExportProcedures = True;
         mb.ExportInfo.ExportFunctions = True;
         mb.ExportInfo.ExportTriggers = True;
         mb.ExportInfo.ExportViews = True;

         cmd.Connection = con;
         con.Open();
         MemoryStream ms = new MemoryStream();
         mb.ExportToMemoryStream(ms); // ERROR: at this Out of Memory //
         ms.Position = 0;
         MemoryStream mszip = new MemoryStream();
         using (GZipStream zip = new GZipStream(mszip, CompressionMode.Compress, true))
          {
           byte[] buffer = ms.ToArray(); 
           zip.Write(buffer, 0, buffer.Length);
           zip.Flush();
           }
           mszip.Position = 0;
           // Client.PutObject('myflename.dump.Gzip',mszip);
           con.Close();
          }
         }
         con.Close();
        }
![capture](https://user-images.githubusercontent.com/33679589/40540984-aa34a5fe-6037-11e8-9477-288056310fd1.PNG)

**Comment by adriancs2** [comment]
Yupe, that's the limitation of exporting to memory stream.
Try export it to a physical file.

**Comment by sridhargoshika** [comment]
Exporting it to a physical file when the database is very large is also throwing below exceptions, Is there any way to tell `mb.Export..` to include all tables but exclude this list of tables?

- Fatal error encountered during data read.
- Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

**Comment by adriancs2** [comment]
If the timeout is caused by MySQL connection, then you can increase the duration of the connection timeout by adding the following connection string option:
```sql
ConnectionTimeout=15
```
The length of time (in seconds) to wait for a connection to the server before terminating the attempt and generating an error. Source: [https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html](https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html)

Example:
```
server=localhost;user=root;pwd=1234;database=test;ConnectionTimeout=300;
```

If the timeout is caused by ASP.NET connection timeout, increase the connection timeout of ASP.NET.
If you are developing in WinForm or WPF desktop app, try execute MySqlBackup.NET on another separate thread, such as by using BackgroundWorker.

**Comment by adriancs2** [comment]
Include or excluding tables, you can refer this wiki page:
https://github.com/MySqlBackupNET/MySqlBackup.Net/wiki/Conditional-Rows-Export-for-Each-Table

**Comment by sridhargoshika** [comment]
Thank You for the quick response,
There is no errors on import of .sql file, but in my case i have a large database so using GZipStream compressed.
I downloaded MySQL backupup file(.gz) and trying to import into new database, but I am getting below error when importing into new MySQL database( i am using SQLyog). I posted my code in the question.

Error Code: 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1

**Comment by adriancs2** [comment]
MySqlBackup.NET is not used for MariaDB.

**Comment by sridhargoshika** [comment]
It seems like MySqlBackup.Net is working fine for MariaDB as well. For import .sql is working very well but .gz import is not working, getting Error Code: 1064 ( I tried import using SQLyog)

**Comment by adriancs2** [comment]
.gz is a compressed file. Just like a .zip file. I believe you need to decompressed the file for MySqlBackup.NET to understand the content.

**Comment by OctavioGtz** [comment]
Same throw here but the issue comes when importing from File Blob seems to have an issue not freing memory. Anybody can help?

private void BTN_Restore_Click(object sender, EventArgs e)
        {
            MiConexion.Open();
            if (MiConexion.State == ConnectionState.Open)
            {
                using (MiConexion)
                {
                    using (MySqlCommand MiComando = new MySqlCommand())
                    {
                        using (MySqlBackup MiBackup = new MySqlBackup(MiComando))
                        {
                            MiComando.Connection = MiConexion;
                            MiBackup.ImportFromFile(@"C:\Templ\Bakckup.sql");
                            MiConexion.Close();
                        }
                    }
                }
            }

**Comment by adriancs2** [comment]
Are you using the latest the version of MySqlBackup.net?
In the latest version, the memory is clear immediately after executing every single SQL query.
If the problem still exists, this might be caused by the blob size. The blob data's length is too long to be handle by .NET Language.

**Comment by OctavioGtz** [comment]
V2.0.12 for NetFwk 4.6.1 seem to worked properly.

Thank you!

**Comment by adriancs2** [comment]
Hi, can you try the following setup:

1st, make your program to be compiled in x64 bit binary.
2nd, at the **app.config**, add the following:
```
<configuration>
  <runtime>
    <gcAllowVeryLargeObjects enabled="true" />
  </runtime>
</configuration>
```
