### ISSUE TITLE
MySqlBackupNET doesn't export Stored Procedures

### ISSUE THREAD

**Issue by WilbertE** [MySqlBackupNET/MySqlBackup.Net#23]
Hi,

First of all, great lib. Simple and clean.

However I'm having some troubles with the export function as it doesn't export any stored procedures.

There is this line:
```
-- 
-- Dumping procedures
-- 
```
but no stored procedures get exported.

I installed the Nuget package (MySqlBackup.Net 2.0.12) but because I'm using MySQL 8.0.11 which uses the 'caching_sha2_password' authentication type I get an error that the mysql.data.dll installed with MySqlBackup.Net does not support that authentication type. 

So I installed Nuget package 'MySql.Data 8.0.12 from Oracle' to overwrite the mysql.data.dll which does support 'caching_sha2_password'. 

After that exporting the database works, but the stored procedures are not in the export.
I tried adding `mb.ExportInfo.ExportProcedures = true;` but even with this, there are no stored procedures exported. There is no error either. Just an output with all the tables.

I don't know if the other mysql.data version has to do anything with it, but I add this information because it might.

Do you have any idea what the problem can be?

**Comment by WilbertE** [comment]
Ok. I feel like the dumbest idiot in history. I connected with a user without the rights to access stored procedures.

**Comment by phil-w** [comment]
You and me too. Good point.
