### ISSUE TITLE
Exception "System.OutOfMemoryException" while memory stream exporting DB

### ISSUE THREAD

**Issue by jpmaistrebazin** [MySqlBackupNET/MySqlBackup.Net#26]
Hello,

During export, an exception "System.OutOfMemoryException" throwing.

Stack Trace
`System.IO.MemoryStream.set_Capacity(Int32 value) à System.IO.MemoryStream.EnsureCapacity(Int32 value) à System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count) à System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) à System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count) à System.IO.TextWriter.WriteLine(String value) à MySql.Data.MySqlClient.MySqlBackup.Export_RowsData_Insert_Ignore_Replace(String tableName, String selectSQL) à MySql.Data.MySqlClient.MySqlBackup.Export_RowsData(String tableName, String selectSQL) à MySql.Data.MySqlClient.MySqlBackup.Export_Rows(String tableName, String selectSQL) à MySql.Data.MySqlClient.MySqlBackup.Export_TableRows() à MySql.Data.MySqlClient.MySqlBackup.ExportStart() à MySql.Data.MySqlClient.MySqlBackup.ExportToMemoryStream(MemoryStream ms, Boolean resetMemoryStreamPosition) à MySql.Data.MySqlClient.MySqlBackup.ExportToMemoryStream(MemoryStream ms) à Pts.Framework.App.Autosoft.Database.Helper.DumpDatabaseWithEncrypt(String file, String connectionString) à AeOOut.For_SavPro.Act_Sav()`

I can't use export to file because I can't write on disk…

I have 4GB of RAM, so I'm supposing that it's not a RAM problem.

**Comment by jpmaistrebazin** [comment]
Exception throw on windows 7 x86

**Comment by adriancs2** [comment]
I'm currently don't have the fix at the moment. I have tried a simple test:
```
StringBuilder sb = new StringBuilder(1024 * 1024 * 1024);
```
The program throws the same error of System.OutOfMemoryException.
It does not work.
I will come back to this if I found the solution.

**Comment by adriancs2** [comment]
Hi, can you try the following setup:

1st, make your program to be compiled in x64 bit binary.
2nd, at the **app.config**, add the following:
```
<configuration>
  <runtime>
    <gcAllowVeryLargeObjects enabled="true" />
  </runtime>
</configuration>
```
