### ISSUE TITLE
Is it possible to introduce async versions of import/export methods?

### ISSUE THREAD

**Issue by sokolowskip** [MySqlBackupNET/MySqlBackup.Net#29]

**Comment by adriancs2** [comment]
You can try using BackgroundWorker (namespace: System.ComponentModel)
You can visit this wiki page: https://github.com/MySqlBackupNET/MySqlBackup.Net/wiki/Using-Progress-Report-With-Export-Backup
which demonstrates the implementation of multi-thread using BackgroundWorker.

**Comment by adriancs2** [comment]
Are you able to contribute the code patch for implementing async functionality?

**Comment by sokolowskip** [comment]
I would like to do it, but i wonder how it should be done. 
I was thinking about using the async versions of .net functions (e.g. SqlCommand.ExecuteNonQueryAsync instead of SqlCommand.ExecuteNonQuery). But this approach seems to cause lots of code duplications.
Another way is wrapping all public methods from MySqlBackup in something like Task.Run. But this seems to be unreasonable. It's better to allow end users to do that on their own.

What do you think? Do you have any idea how introducing the async api can be achieved?

**Comment by adriancs2** [comment]
I will try this out at later time. I'll get back to this if I found any clues.

**Comment by Apskaita5** [comment]
Not a good idea:
- would brake compatibility with .net versions < 4.5;
- can easily write an async/await wrapper  (see https://stackoverflow.com/questions/26717075/way-to-creating-async-wrapper), however the backup and restore methods are internally strictly synchronous (cannot do that in parts in arbitrary order) plus you would pass open sql conn to method (not sure how would that work with variable scoping) which means that async/await pattern is not recommended in this case (see the discussion in the same link).

**Comment by adriancs2** [comment]
> Not a good idea:

Thanks for the info.
