### ISSUE TITLE
Foreign keys and table restore order

### ISSUE THREAD

**Issue by Apskaita5** [MySqlBackupNET/MySqlBackup.Net#31]
I'm porting the library to use with SQLite and noticed possible issue with foreign keys that make the table create order important. In MySQL foreign keys are created within table create statement. If the table referenced by a foreign key is not already in place, it would cause an exception. Same issue as with views/ methods dependencies.
Not sure, whether that should be handled by backup or restore.
Also capability to export/import only some tables creates dependency nightmare.

**Comment by adriancs2** [comment]
Can you try the following
```
SET FOREIGN_KEY_CHECKS=0;
INSERT.......
INSERT .......
INSERT.......
INSERT.......
SET FOREIGN_KEY_CHECKS=1;
```
and if this solved your problem?
If yes I will include a new option for temporary disabling the foreign key checking while restoring the database.

**Comment by Apskaita5** [comment]
Nope. The problem is CREATE TABLE order. You cannot create a table that references not yet existent table.
The same is with dependent routines.
I solved the problem for sqlite by recursive table dependences analysis. TableCreate method first invokes the same method on the referenced tables. The solution still makes impossible to backup databases with circular references, but I don't think that would be a frequent case. At least it's not important for me. However the mysql is harder due to the routines. Not sure how to extract calls to dependent routines.

**Comment by adriancs2** [comment]
Can you provide 5 CREATE TABLE queries that have dependent foreign key on each other which will generate the error that you've mentioned. I will use that as sample data for solving this problem. Thanks.

**Comment by Apskaita5** [comment]
Try to create table icons before table companies and you will get the error.

CREATE TABLE DoomyDatabaseName.companies(id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, name CHAR(255) NOT NULL, registrationcode CHAR(50) NOT NULL, address CHAR(255) NOT NULL, phone CHAR(20) NOT NULL, email CHAR(255) NOT NULL, website CHAR(255) NOT NULL, dponame CHAR(255) NOT NULL, dpophone CHAR(20) NOT NULL, dpoemail CHAR(255) NOT NULL, contactpersonposition CHAR(255) NOT NULL, recordsofprocessingarepublic TINYINT UNSIGNED NOT NULL, insertedat DATETIME NOT NULL, insertedby CHAR(255) NOT NULL, updatedat DATETIME NOT NULL, updatedby CHAR(255) NOT NULL) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE DoomyDatabaseName.icons(id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, companyid INT UNSIGNED, iconbytes BLOB NOT NULL, KEY `icons_companyid_index` (`companyid`), CONSTRAINT `icons_companyid_index` FOREIGN KEY `icons_companyid_index`(`companyid`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

**Comment by adriancs2** [comment]
I am able to identify any tables that have foreign keys references by executing the following SQL:
```
select table_name, referenced_table_name
from information_schema.key_column_usage
where constraint_schema='DoomyDatabaseName' and referenced_table_name IS NOT NULL;
```
with this, I can rearrange the CREATE TABLE in a specific order that will avoid the foreign key dependency error.

**Comment by Apskaita5** [comment]
That will not work in hosting environment with limited priviledges.

⁣Get BlueMail for Android ​

**Comment by adriancs2** [comment]
According to MySQL documentation,
https://dev.mysql.com/doc/refman/8.0/en/information-schema-introduction.html

At the section: **INFORMATION_SCHEMA and Privileges**

> Each MySQL user has the right to access these tables, but can see only the rows in the tables that correspond to objects for which the user has the proper access privileges. In some cases (for example, the ROUTINE_DEFINITION column in the INFORMATION_SCHEMA ROUTINES table), users who have insufficient privileges see NULL. These restrictions do not apply for InnoDB tables; you can see them with only the PROCESS privilege.
> 
> The same privileges apply to selecting information from INFORMATION_SCHEMA and viewing the same information through SHOW statements. In either case, you must have some privilege on an object to see information about it.
> 
> 

If a user has the privilege to "SELECT" data from a table, i.e. TABLE-A, then this user can get the information about "TABLE-A" at INFORMATION_SCHEMA.

**Comment by Apskaita5** [comment]
Ok.

**Comment by adriancs2** [comment]
Hi, you may test the following build which I have already patched the code for solving the foreign key dependency "CREATE TABLE" order. You may provide feedback after testing this build
[MySqlBackup.NET_Debug_Issue_31_v1.zip](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/2951842/MySqlBackup.NET_Debug_Issue_31_v1.zip)

**Comment by adriancs2** [comment]
A new release is published. version 2.2
you may download and have a try

**Comment by adriancs2** [comment]
Hi, a new version (v2.3) is released, where this problem is resolved. You may try it out.
