### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by gauravnewton** [MySqlBackupNET/MySqlBackup.Net#33]
When i click button to backup db it says access denied as runtime error how to grant administrator access

**Comment by adriancs2** [comment]
create another MySQL user with admin privileges. Use this user for running MySQLBackup.net

**Comment by hirocsingh** [comment]
Possible, I was having the the same problem with SQL Server backup. You might need to change the permissions of the backup file if you are working with windows.

**Comment by adriancs2** [comment]
> Possible, I was having the the same problem with SQL Server backup. You might need to change the permissions of the backup file if you are working with windows.
This has nothing to do with MySqlBackup.NET, you should ask it at: https://www.stackoverflow.com in stead.

**Comment by gauravnewton** [comment]
I found the solution the path i am providing to back up was not proper formatted .... That's why i am getting access denied error. I just want to say the developer update the error message for this issue in exception.....
