### ISSUE TITLE
Add SQLite support

### ISSUE THREAD

**Issue by Apskaita5** [MySqlBackupNET/MySqlBackup.Net#34]
Not an issue. Functionality suggestion.

I've completed porting MySqlBackup.Net to SQLite. See repository https://github.com/Apskaita5/SQLiteBackup
Still needs some refactoring because I just copied your code and only made necessary changes to make it work with sqlite. Needs extensive testing also.
Would you like to merge projects?

**Comment by adriancs2** [comment]
Hi, the SQLiteBackup is awesome.

About merging both projects: Both projects used difference tools (MySQL.DATA, System.Data.SQLite) and different namespace, how is this to be done by merging both codes?

**Comment by Apskaita5** [comment]
By adding sqlite backup to your solution as a project? Just to find same tools for different db engines in one place. Maybe later add common interface for DI.

⁣Get BlueMail for Android ​

**Comment by adriancs2** [comment]
I am a fan of using SQLite too. How about create a organization? I would like to join your project as a developer.

**Comment by Apskaita5** [comment]
What do you mean by organization? I've added you as a collaborator in sqlite backup project.

**Comment by adriancs2** [comment]
New organization can make the URL of the project becomes something like this:
https://github.com/SQLiteBackupNET/SQLiteBackup.NET
![Untitled](https://user-images.githubusercontent.com/646615/54473308-db740080-4810-11e9-9d0e-754f80a405c8.jpg)
