### ISSUE TITLE
Too high values on ExportProgressChanged event

### ISSUE THREAD

**Issue by tedebus** [MySqlBackupNET/MySqlBackup.Net#35]
Version: 2.1.3.59
Runtime: v4.0.30319
Project downloaded using GIT and compiled using Visual Studio 2017 Community version 15.9.8
No changes on source code

Issue: The ExportProgressChanged event carries incorrect information about the progress of the exported rows.

This is the code used for data export:
```
[...]
 using (MySqlBackup mb = new MySqlBackup(cmd))
 {
           mb.ExportInfo.AddCreateDatabase = true;
           mb.ExportInfo.ExportTableStructure = true;
           mb.ExportInfo.ExportRows = true;
           mb.ExportInfo.RecordDumpTime = true;
           mb.ExportInfo.ResetAutoIncrement = false;
           mb.ExportInfo.MaxSqlLength = 104857600; //100MB
           mb.ExportInfo.ExportFunctions = true;
           mb.ExportInfo.ExportProcedures = true;
           mb.ExportInfo.ExportTriggers = true;
           mb.ExportInfo.ExportEvents = true;
           mb.ExportInfo.ExportViews = true;
           mb.ExportInfo.ExportRoutinesWithoutDefiner = false;
           mb.ExportInfo.RowsExportMode = RowsDataExportMode.Insert;
           mb.ExportInfo.WrapWithinTransaction = false;
           mb.ExportProgressChanged += Mb_ExportProgressChanged;
           mb.ExportCompleted += Mb_ExportCompleted;
           mb.ExportToFile(Path.Combine(filePath));
 }
[...]
```
where Mb_ExportProgressChanged is:

```
 private void Mb_ExportProgressChanged(object sender, ExportProgressArgs e)
 {
             Console.WriteLine(e.CurrentRowIndexInAllTables + " " + e.TotalRowsInAllTables);
 }
```

This is the console result:
```
2459 26795
5856 26795
9252 26795
12594 26795
16142 26795
19874 26795
23169 26795
24708 26795
26060 26795
27930 26795   <------
```
As you can see the last value of _CurrentRowIndexInAllTables_  is higher than _TotalRowsInAllTables_
I expected to have same value.

**Comment by tedebus** [comment]
Other issue on the same test: 
if I use _RowsDataExportMode.OnDuplicateKeyUpdate_ instead of _RowsDataExportMode.Insert_ the result is:
```
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
0 26795
```

**Comment by adriancs2** [comment]
Thanks for the report, will be fixed in the next release.

**Comment by tedebus** [comment]
Perfect. 
Thanks for your great work. 
He saved me from a lot of work! ;)

**Comment by adriancs2** [comment]
Hi, I have made some changes, can you retry with this version?
[MySqlBackup.NET_Debug_Issue35_v1.zip](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/3270112/MySqlBackup.NET_Debug_Issue35_v1.zip)

**Comment by adriancs2** [comment]
Hi, I have released a new version which will solve this problem.

There are 2 ways of getting the total rows.

1st method
```
select table_name, table_rows from Information_Schema.tables where table_schema='test';
or
show table status;
```

2nd method
```
select count(*) from `table_name`;
```

1st method is fast, but the value is just an approximation value.
2nd method is accurate, but slow.

Originally, MySqlBackup.NET is using 1st method to get the total rows.
but now, I have included both methods to choose from.

You can define the method to be used at `ExportInfo.GetTotalRowsMode`. Example:
```c#
using (MySqlConnection conn = new MySqlConnection(constring))
{
    using (MySqlCommand cmd = new MySqlCommand())
    {
        using (MySqlBackup mb = new MySqlBackup(cmd))
        {
            cmd.Connection = conn;
            conn.Open();
            mb.ExportInfo.ExportInfo.GetTotalRowsMode= GetTotalRowsMethod.SelectCount;
            mb.ExportToFile(file);
        }
    }
}
```

**Comment by adriancs2** [comment]
I have included the test section inside the test app which can be obtained here:
https://github.com/MySqlBackupNET/MySqlBackup.Net/releases

Test App > Menu > Test > Progress Report Export
