### ISSUE TITLE
"mysql_error_log.txt" in application directory

### ISSUE THREAD

**Issue by qa7720** [MySqlBackupNET/MySqlBackup.Net#37]
When using the component a file named "mysql_error_log.txt" with the content "hi :)" is created in the application directory.
See MySqlBackup/MySqlBackup.cs -> Line 134
`System.IO.File.WriteAllText("mysql_error_log.txt", "hi :)");`

When uninstalling an application that includes the MySqlBackup.Net component, this file remains in the application directory. This will prevent the installer from removing the directory.

I assume it's a leftover from a debugging session, so is it possible to remove this line?

Thanks

**Comment by adriancs2** [comment]
This line is unnecessary and should be deleted.
thanks for the report.

**Comment by adriancs2** [comment]
Hi, this issue is fixed :)
thanks

**Comment by adriancs2** [comment]
You may try the new release v2.2.1

**Comment by adriancs2** [comment]
Hi, a new version (v2.3) is released, where this problem is resolved. You may try it out.
