### ISSUE TITLE
Procedure Restore errors

### ISSUE THREAD

**Issue by fpradom** [MySqlBackupNET/MySqlBackup.Net#38]
I tryed to restore Stored Procedures with the Test Application and have SQL syntax errors on all procedures.

The Import_Routines() method gives exception errors for all of them.

I have made a Backup file named Test.sql that is attached in txt format
[Test.txt](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/3023633/Test.txt)

The resulting errors are displayed in the Error_Report.txt fila tha is also attached.
[Error_Report.txt](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/3023640/Error_Report.txt)

Have you any suggestion to avoid this problem?

Many thanks for your attention

F. Prado

**Comment by adriancs2** [comment]
This error is newly created in the last release which I have forget to handle the changes of the Delimiters.
I have dropped the support for handling the dependencies of Function, Procedure, Trigger and Events.
You may try the new release v2.2

**Comment by fpradom** [comment]
Hallo Adrian,

I have tested the new versión and all runs OK.

 

The only dificult is that I musted comment line 1309 “_sbImport.Clear();”  

This line give me an “System.Text.StringBuilder not contains a definition of ‘Clear’

In any case, with the next line 1310 “_sbImport = new StringBuilder();” the variable is cleares.

 

Many thanks for your attention

 

F. Prado

 

De: Adrian Voo [mailto:notifications@github.com] 
Enviado el: domingo, 07 de abril de 2019 18:25
Para: MySqlBackupNET/MySqlBackup.Net
CC: fpradom; Author
Asunto: Re: [MySqlBackupNET/MySqlBackup.Net] Procedure Restore errors (#38)

 

Closed #38 <https://github.com/MySqlBackupNET/MySqlBackup.Net/issues/38> .

**Comment by adriancs2** [comment]
I see. Thanks for the info.

**Comment by fpradom** [comment]
Hi Adrian,

 

For he case it can be usefull for you, I inform you that I have made litle changes to your code for my use.

 

ImportCompleteArgs: 

 

using System;

using System.Collections.Generic;

using System.Text;

 

namespace MySql.Data.MySqlClient

{

    public class ImportCompleteArgs

    {

        // Added to control the Import ProcessEndType

        MySqlBackup.ProcessEndType _completionType = MySqlBackup.ProcessEndType.UnknownStatus;

 

        /// <summary>

        /// The starting time of import process.

        /// </summary>

        public DateTime TimeStart;

 

        /// <summary>

        /// The ending time of import process.

        /// </summary>

        public DateTime TimeEnd;

 

        /// <summary>

        /// Enum of completion type

        /// </summary>

        public enum CompleteType

        {

            Completed,

            Cancelled,

            Error

        }

 

        /// <summary>

       /// Indicates whether the import process has error(s).

        /// </summary>

        public bool HasErrors { get { if (LastError != null) return true; return false; } }

 

        /// <summary>

        /// The last error (exception) occur in import process.

        /// </summary>

        public Exception LastError = null;

 

        // <summary>

        /// The completion type of current import processs.

        /// </summary>

        // Replaced to control the correct CompletedType

        //public CompleteType CompletedType = CompleteType.Completed;

        public MySqlBackup.ProcessEndType CompletionType

        {

            get { return _completionType; }

            set { this._completionType = value; }

        }

 

        /// <summary>

        /// Total time used in current import process.

        /// </summary>

        public TimeSpan TimeUsed

        {

            get

            {

                TimeSpan ts = new TimeSpan();

                ts = TimeEnd - TimeStart;

                return ts;

            }

        }

 

    }

}

 

In MySqlBackup

 

Added Line 1560  “arg.CompletionType = processCompletionType;”

In order to implement the above change in ImportCompleteArgs

 

Added 2 new methods to implement the possibility to cancel the process by the user:

 

 

        public void Cancel()

        {

            if (currentProcess == ProcessType.Export)

            {

                StopAllProcess();

            }

            else if (currentProcess == ProcessType.Import)

            {

                StopAllProcess();

                CloseConnection();

            }

        }

 

        void CloseConnection()

        {

            if (Command.Connection != null)

            {

                Command.Connection.Close();

                Command.Connection.Dispose();

            }

 

            if (Command != null)

                Command.Dispose();

 

        }

 

Many thank for your nice application and best regards

 

F.Prado

De: Adrian Voo [mailto:notifications@github.com] 
Enviado el: viernes, 12 de abril de 2019 4:50
Para: MySqlBackupNET/MySqlBackup.Net
CC: fpradom; Author
Asunto: Re: [MySqlBackupNET/MySqlBackup.Net] Procedure Restore errors (#38)

 

I see. Thanks for the info.
