### ISSUE TITLE
Error on restore events

### ISSUE THREAD

**Issue by fbua** [MySqlBackupNET/MySqlBackup.Net#40]
Trying to restore a database backup with an event defined I got this message:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER |
CREATE EVENT `EventDay1` ON SCHEDULE EVERY 1 YEAR STARTS ' at line 1
But trying to restore the same dump with mysql command the restore works fine.

**Comment by adriancs2** [comment]
Post the full SQL query command

**Comment by fbua** [comment]
> 
> 
> Insufficient information. Try post the full SQL query command.

Hi, this is the SQL query dumped for the event:

-- 
-- Dumping events
-- 

DROP EVENT IF EXISTS `AggiornaDatePiscina`;
DELIMITER |
CREATE EVENT `AggiornaDatePiscina` ON SCHEDULE EVERY 1 YEAR STARTS '2019-01-01 03:00:00' ON COMPLETION PRESERVE ENABLE COMMENT 'Aggiona le date di funzionamento delle piscine' DO BEGIN
	UPDATE piscina SET InFunzioneDal = DATE_ADD(InFunzioneDal, INTERVAL 1 YEAR) WHERE InFunzioneDal IS NOT NULL;
	UPDATE piscina SET InFunzioneAl = DATE_ADD(InFunzioneAl, INTERVAL 1 YEAR) WHERE InFunzioneAl IS NOT NULL;
END |
DELIMITER ;

**Comment by adriancs2** [comment]
I have tried to recreate the problem that you mentioned. But it appears to be no error. 
It seems that you are using version 2.1 which will syntax error while handling routines such as PROCEDURES, FUNCTIONS, TRIGGERS and EVENTS.
https://github.com/MySqlBackupNET/MySqlBackup.Net/wiki/Change-Log

Here is the sample project project that attempt to recreate your error:
Note: the following project uses latest version of MySqlBackup.NET (v2.2.1)
[MySqlBackup.NET_Issue_40_v1.zip](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/3110211/MySqlBackup.NET_Issue_40_v1.zip)

**Comment by fbua** [comment]
> 
> 
> It seems that you are using version 2.1 which will cause syntax error while handling routines such as PROCEDURES, FUNCTIONS, TRIGGERS and EVENTS.
> https://github.com/MySqlBackupNET/MySqlBackup.Net/wiki/Change-Log
> 
> Here is the sample project project that attempt to recreate your error:
> The following project executed your sample SQL queries without error. It uses latest version of MySqlBackup.NET (v2.2.1)
> [MySqlBackup.NET_Issue_40_v1.zip](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/3110211/MySqlBackup.NET_Issue_40_v1.zip)

Thank you for your reply.
I already tried with the latest version of library, but I use the DevArt Express connector in my project.
Maybe the problem is related to this?

**Comment by adriancs2** [comment]
In the documentation of DevArt for MySql:
https://www.devart.com/dotconnect/mysql/docs/
I found the class object of "MySqlDump" under the section:
Devart.Data.MySql Assembly > Devart.Data.MySql Namspace > Classes > MySqlDump
with description as follow:

> Serves to store a database or its parts as a script and to restore database from the generated script.

But, "MySqlDump" is not found in the Express version, perhaps in the full (Commercial) version.

I believe that if you purchase the full version, you can simply use the build-in "MySqlDump" function which will perform the same thing similar to MySqlBackup.NET and oracle's version of "MySqlDump".

I have tried to play around with code of DevArt Express MySQL for searching the possibilities of executing script (Create Function, Procedure, Event, Trigger). It seems the DevArt-Express version does not support script execution.

Below is the project that I used to test around the "Devart.Data.MySql.dll (express version)" in attempt to find the Class object in the Express version to execute script. You can download it and play around with it. If you found the solution for executing the script, you may post back here.
[MySqlBackup.NET_Issue_40_v2.zip](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/3119655/MySqlBackup.NET_Issue_40_v2.zip)

**Comment by adriancs2** [comment]
According to the Edition comparison page:
https://www.devart.com/dotconnect/mysql/editions.html

MySqlScript class is not available in Free edition.
MySqlDump class is available in Professional & Developer edition.

**Comment by adriancs2** [comment]
My personal thought: Since C# (.NET) and MySQL routines (function, procedure, trigger, event) are both processed at server side, you can migrate your MySQL routines to C# (.NET) side. Use MySQL only for data storage, and process any data at C# side.

Unless you're process data at client side such as Javascript, then MySQL routines will help to accelerate and secure the data calculation/processing. It reduces the time travelling between client side and server side.

But this is just my personal view, it might not suite your environment.

**Comment by fbua** [comment]
Thank you for your reply.
I use the Express version of dotConnect. I searched and found your library because this version not support database dump, as well as script execution, etc.
I saw in your code that you use MySqlCommand class to execute the queries in dump file.
Maybe the event restore is appended to command in a way that causes the error?

If I have some time I'll try to check the query that is executed and I'll try to found a solution. In that case I'll send you my solution

Thank you

**Comment by adriancs2** [comment]
In the creation of EVENT, there are actually 3 separate SQL commands

1st > DELIMITER |
2nd > CREATE EVENT .............. END |
3rd > DELIMITER ;

In order for the EVENT to be created successfully, the delimiter is required to be changed. But MySqlCommand is not able to recognize the 1st SQL command (DELIMETER) and refuse to react.

**Comment by fbua** [comment]
> 
> 
> In the creation of EVENT, there are actually 3 separate SQL commands
> 
> 1st > DELIMITER |
> 2nd > CREATE EVENT .............. END |
> 3rd > DELIMITER ;
> 
> In order for the EVENT to be created successfully, the delimiter is required to be changed. But MySqlCommand is not able to recognize the 1st SQL command (DELIMETER) and refuse to react.

Ok I understood the problem.
I'll try to find a workaround and, if exists, I'll send it to you.
