### ISSUE TITLE
What happens with concurrency?

### ISSUE THREAD

**Issue by gparadelo** [MySqlBackupNET/MySqlBackup.Net#41]
Hi, thanks for your hard work, it saved me from a lot of issues I was having with mysqldump.
One question: What happens if the database is accesed or modified while I'm doing the back up? Do I need to lock the tables befores starting ?

**Comment by adriancs2** [comment]
You might want to temporary shutdown your application (web server) until the backup and restore process completed. Yes, you can also perform LOCK TABLES WRITE in the backup/restore process.

**Comment by gparadelo** [comment]
Great, thanks.
