### ISSUE TITLE
Weird exception after making a new backup

### ISSUE THREAD

**Issue by gparadelo** [MySqlBackupNET/MySqlBackup.Net#43]
I'm getting a FileLoadException when executing Type.GetType after having created a backup using the library. This only happens after the backup is created, there is no issue before. 

I've isolated the function that if executed causes the error to happen later and its `new MySqlBackup(cmd)` where cmd is  `MySql.Data.MySqlClient.MySqlCommand`.

It's possible that the problem is caused by the line 
`AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;` ,
executed in the constructor of MySqlBackup.

**Comment by adriancs2** [comment]
I think yes. That line can be excluded.
It is not necessary to have it.
I will drop that line in the next release.

**Comment by adriancs2** [comment]
Hi, a new version (v2.3) is released, where this problem is resolved. You may try it out.
