### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by MincDev** [MySqlBackupNET/MySqlBackup.Net#44]
When dumping a very large database, the above error appears and only part of the database is dumped. If I keep trying, the database eventually finishes the backup. However, The software does not have someone in front of it at all times. What could be the cause of this?

**Comment by adriancs2** [comment]
I have made some changes, can you try this version:
[MySqlBackup.NET_Debug_Issue43_v1.zip](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/3270092/MySqlBackup.NET_Debug_Issue43_v1.zip)

**Comment by MincDev** [comment]
Hi @adriancs2 

Thank you for your assistance in this regard. Unfortunately, it still fails. :( My database that needs to be backed up is about 210MB. The error is weird because it seems that it fails at different points of the backup. I ran it this morning and it failed only dumping 47MB. Then reran and it dumped 123MB. If I keep trying without closing the application, the database will eventually finish dumping the full 210MB. 

Small databases have no issue.

Are you familiar with this error? Am I maybe doing something wrong? This is how I am connecting and using MySqlBackup.

```
public void Backup(string Location)
        {
            try
            {
                string fileName = ODatabase.Database + DateTime.Now.ToString("yyMMdd_HHmmss") + ".sql";
                string file = Location + fileName;
                if (Connect())
                {
                    using (MySqlCommand cmd = new MySqlCommand())
                    {
                        using (MySqlBackup mb = new MySqlBackup(cmd))
                        {
                            cmd.Connection = conn;
                            cmd.CommandType = CommandType.Text;
                            mb.ExportToFile(file);
                        }
                    }

                    Disconnect();
                }
            }
            catch(Exception ex)
            {
                Disconnect();
                IO.CreateLogEntry(IO.ERROR_LOG, "MySql Backup Error : " + ex.Message, Parent);
            }
        }
```

Let me know if you need more than this.

**Comment by adriancs2** [comment]
Are you able to collect any exception/error message which provides more information about the error?

**Comment by MincDev** [comment]
@adriancs2 after doing a clean and rebuild of my project it seems to work now. I was able to create a backup successfully 3 times in a row without getting the error thrown. I will keep an eye on it for a few more days and provide full details on the error if it happens again. 

Thank you so much for the assistance and a great library!

**Comment by adriancs2** [comment]
Hi, new version released (v2.3), this problem should be resolved. you may test it in your environment and see if the problem still exists :)

**Comment by MincDev** [comment]
Perfect timing! Our monthly process will be running tomorrow. I will update immediately. :)

Thanks!

**Comment by MincDev** [comment]
Thanks, no more issues ! :)
