### ISSUE TITLE
Tables missing from export

### ISSUE THREAD

**Issue by djgreedo** [MySqlBackupNET/MySqlBackup.Net#45]
When exporting a schema, some of the tables are not exported.

- I can find nothing these missing tables have in common or anything making them different to the rest of the tables on the database (via Schema Inspector)
- Running mysqldump from the server exports all tables
- Exporting from MySql Workbench exports all tables
- Default settings used in the export code (I used the sample code posted here with no changes)
- No exception is thrown.
- Have tried exporting without rows and the same tables were missing
- MySqlData 8.0.16
- MySqlBackup v 2.2.1
- Same results whether exporting from the remote database or from a local copy
- Engine is InnoDB
- The table data is not in the exported file, so my issue is with export, not the subsequent import.
- FWIW I have tried on two different computers with the same results

Here is the create table code for one of the tables that doesn't export:
`CREATE TABLE `plugin` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(16) NOT NULL,
  `name` varchar(64) NOT NULL,
  `description` varchar(256) DEFAULT NULL,
  `copyof` int(10) unsigned DEFAULT NULL,
  `createdon` datetime DEFAULT NULL,
  `changedon` datetime DEFAULT NULL,
  `deletedon` datetime DEFAULT NULL,
  `changedby` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_UNIQUE` (`code`),
  KEY `fk_plugin_copyof_idx` (`copyof`),
  CONSTRAINT `fk_plugin_copyof` FOREIGN KEY (`copyof`) REFERENCES `plugin` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=279 DEFAULT CHARSET=utf8;
`

**Comment by adriancs2** [comment]
I have made some changes to the code, can you try this version:
[MySqlBackup.NET_Debug_Issue43_v1.zip](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/3270090/MySqlBackup.NET_Debug_Issue43_v1.zip)

**Comment by djgreedo** [comment]
Thank you for looking into this!

The .DLL you included in your above code does fix this issue for me. I now get all the tables in my export (I was previously missing 3 tables out of 113). Your test application did not work for me - there was an issue with the date formats, but importing the .DLL into my own project worked.

Thank you!

**Comment by adriancs2** [comment]
New version (v2.3) released. this should solved the problem :)
