### ISSUE TITLE
Export error guid? help base size 1gb

### ISSUE THREAD

**Issue by jommb** [MySqlBackupNET/MySqlBackup.Net#49]
does not load the database with such an error
Необработанное исключение типа "System.FormatException" в MySqlBackup.dll
Дополнительные сведения: Нераспознанный формат идентификатора GUID.
error after 30sec in mb.ExportToFile("ccvt_bot.sql");

`using (MySqlConnection conn = new MySqlConnection("server=123.123.123.123;user=root;pwd=123123;database=ccvt_bot;charset=utf8;convertzerodatetime=true;"))
            {
                using (MySqlCommand cmd = new MySqlCommand())
                {
                    using (MySqlBackup mb = new MySqlBackup(cmd))
                    {
                        cmd.Connection = conn;
                        conn.Open();
                        cmd.CommandTimeout = 30;
                        mb.ExportToFile("ccvt_bot.sql");
                        conn.Close();
                    }
                }
            }`

image http://prntscr.com/odmuz6

**Comment by adriancs2** [comment]
What is the data type of the GUID column in your database?
is it `CHAR(36)` or `BINARY(16)`?

If it is `BINARY(16)`, then you can apply the connection string option `OldGuids=true` to resolve this problem. For example:
```
server=localhost;user=root;pwd=1234;database=test;oldguids=true;
```

**Comment by jommb** [comment]
thanks earned
