### ISSUE TITLE
Fatal error encountered during command execution

### ISSUE THREAD

**Issue by SpaceInvader0** [MySqlBackupNET/MySqlBackup.Net#50]
Hi, i am using MySqlBackup.NET, and during import i am getting the following error. 
Any suggestion or similar situation encountered? 

> Message: Fatal error encountered during command execution.
> StackTrace:    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
>    at MySql.Data.MySqlClient.MySqlScript.Execute()
>    at MySql.Data.MySqlClient.MySqlBackup.Import_AppendLineAndExecute(String line)
>    at MySql.Data.MySqlClient.MySqlBackup.Import_ProcessLine(String line)
>    at MySql.Data.MySqlClient.MySqlBackup.Import_Start()
>    at MySql.Data.MySqlClient.MySqlBackup.ImportFromTextReaderStream(TextReader tr, FileInfo fileInfo)
>    at MySql.Data.MySqlClient.MySqlBackup.ImportFromFile(String filePath)
>    at DatabaseBackUp.Program.ImportDatabase(String IPAddress, String DBName, Int32 Type, String Port) in Program.cs:line 1203
> Source: MySql.Data
> TargetSite: MySql.Data.MySqlClient.MySqlDataReader ExecuteReader(System.Data.CommandBehavior)

My code as follows. 
```
using (MySqlBackup mb = new MySqlBackup(cmd))
                        {
                            cmd.Connection = conn;
                            //cmd.CommandTimeout = 0;
                            cmd.CommandTimeout = 1200;
                            conn.Open();
                            mb.ImportFromFile(file);
                            conn.Close();
                            SuccessFlag = true; 
                        }
```
Connection String
`string constring = "SERVER=" + IPAddress + "; DATABASE=" + DBName + ";Port=" + Port + ";USER=123;PASSWORD=xxx;Convert Zero Datetime=True;Charset=utf8;";`

**Comment by adriancs2** [comment]
This error is mostly related to parameters issue. Anyway, there is a problem with your dump file. You might want to check it out. You can also try out stackoverflow.com, you might find some useful info there.

**Comment by SpaceInvader0** [comment]
Hi Adrian, sorry for the late reply. is there a limitation in terms of the number of records i can import using the dll?? Reason for asking is because my table has 70000+ records, for debugging purpose i split the table in 2 and it is able to import successfully. The fatal error occurs only when i try to import 70000 records at one go.

**Comment by adriancs2** [comment]
Hi, @SpaceInvader0 , there is no limit on rows of file size.

**Comment by SpaceInvader0** [comment]
Hi adriancs2, noted and thanks!

**Comment by vortexcv** [comment]
Hello @SpaceInvader0, did you find a solution to this issue? I have the same issue when importing medium size blob entries around 6500 on another pc. but works fine on the dev pc. Both sql databases have utf8mb4 encoding.
If you have found some solution can you share here?
