### ISSUE TITLE
MySqlConnection ambiguous v2.3.0.1 

### ISSUE THREAD

**Issue by benedict1986** [MySqlBackupNET/MySqlBackup.Net#51]
Hi I am using MySqlBackup.Net 2.3.0.1 in my .Net Core 2.2 project. Now I am keep getting the following error. Can you please help to see what could be wrong. I am also using Pomelo.EntityFrameworkCore which seems like uses the MySqlConnector. Thanks

![error](https://user-images.githubusercontent.com/7417859/63211686-0ce55500-c13e-11e9-8abc-e554b6fa4283.png)

**Comment by adriancs2** [comment]
Yes, possible cause of problem is: Pomelo.EntityFrameworkCore uses `MySqlConnector` and MySqlBackup.NET uses `MySql.Data`.

Both `MySqlConnector` and `MySql.Data` has the class of `MySql.Data.MySqlClient`

Here is one of the possible solution:

* You can try create a new folder "MySqlBackup" in your project.
* Download the source code files of `MySqlBackup.NET` and copy paste it into that new folder.

With this, MySqlBackup.NET will be using class library of `MySqlConnector` too.

**Comment by benedict1986** [comment]
Thanks a lot. I solved this by replace Pomelo.EntityFrameworkCore by MySql.Data.EntityFrameworkCore. MySql.Data.EntityFrameworkCore uses MySql.Data, which is the same as MySqlBackup.
