### ISSUE TITLE
InvalidOperationException using 'EnableEncryption'

### ISSUE THREAD

**Issue by doItBinary** [MySqlBackupNET/MySqlBackup.Net#7]
Hi, excellent work, I'm using it without any problem, except when use "EnableEncryption" (and his password) in a medium database (about 42 226 KB), if I put "EnableEncryption" false all the prosess finish without troubles, if my database is shorter the problem still persist
the error is:
`Collection was modified; enumeration operation may not execute`

Source:
`mscorlib`

Stack trace:
`   en System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
    en System.Collections.Generic.List'1.Enumerator.MoveNextRare()
    en MySql.Data.MySqlClient.MySqlBackup.Export_Procedures()
    en MySql.Data.MySqlClient.MySqlBackup.ExportStart()
    en MySql.Data.MySqlClient.MySqlBackup.ExportToFile(String filePath)
    en AppName.ControlDatosExternosClass.<>c__DisplayClass21_0.<CopiaRespaldoDB>b__0(Object   s, DoWorkEventArgs args) en D:\RouteToTheFile\ControlDatosExternosClass.cs:línea 757`

And the line 757 is just: `Backup.ExportToFile(archivo);`

The options I use is:
`Backup.ExportInfo.EnableEncryption = true;
Backup.ExportInfo.EncryptionPassword = "N7vngar45mDy5Cqxa";
Backup.ExportInfo.MaxSqlLength = 3145728;
Backup.ExportInfo.AddCreateDatabase = false;
Backup.ExportInfo.ExportProcedures = true;
Backup.ExportInfo.ExportFunctions = true;
Backup.ExportInfo.ExportTriggers = true;
Backup.ExportInfo.WrapWithinTransaction = true;
Backup.ExportInfo.ExportTableStructure = true;
Backup.ExportInfo.ExportRows = true;
Backup.ExportInfo.GetTotalRowsBeforeExport = true;
Backup.ExportInfo.IntervalForProgressReport = 100;
Backup.ExportInfo.RowsExportMode = RowsDataExportMode.Insert;`

**Comment by adriancs2** [comment]
I am actually thinking of dropping the encryption function. The encryption is performed line by line which will slow the whole process a lot.

Anyway, at the mean time, the better solution which I recommended is: perform the encryption externally after the Export process completed.

There are many encryption algorithms out there. Here is one of the example of implementing AES 256 bit encryption. Source code can be found at: https://www.codeproject.com/Articles/769741/Csharp-AES-bits-Encryption-Library-with-Salt

And if you are going to encrypt your file, you definitely also want to compress the file which will make the file 50%-70% smaller in size.

Example:

**Export**
```C#
string backupFile = "C:\\backup";
string connstr = "server=localhost;user=root;pwd=1234;database=test;";
string password = "1234";

MemoryStream ms = new MemoryStream();

using (MySqlConnection conn = new MySqlConnection(connstr))
{
    using (MySqlCommand cmd = new MySqlCommand())
    {
        using (MySqlBackup mb = new MySqlBackup(cmd))
        {
            conn.Open();
            cmd.Connection = conn;

            mb.ExportToMemoryStream(ms);

            conn.Close();
        }
    }
}

byte[] ba = ms.ToArray();

// 1st Compress the file data
ba = CompressData(ba);

// 2nd Encrypt the file data
ba = AES_Encrypt(ba, password);

// 3rd Write the file data to disk
File.WriteAllBytes(backupFile, ba);
```

**Import**
```C#
string backupFile = "C:\\backup";
string connstr = "server=localhost;user=root;pwd=1234;database=test;";
string password = "1234";

// 1st Read the file bytes
byte[] ba = File.ReadAllBytes(backupFile);

// 2nd Decrypt the file data
ba = AES_Decrypt(ba, password);

// 3rd Decompress the file data
ba = DecompressData(ba);

MemoryStream ms = new MemoryStream(ba);

using (MySqlConnection conn = new MySqlConnection(connstr))
{
    using (MySqlCommand cmd = new MySqlCommand())
    {
        using (MySqlBackup mb = new MySqlBackup(cmd))
        {
            conn.Open();
            cmd.Connection = conn;

            mb.ImportFromMemoryStream(ms);

            conn.Close();
        }
    }
}
```
**Compression**
```C#
using System.IO.Compression;

public byte[] CompressData(byte[] data)
{
    MemoryStream output = new MemoryStream();
    using (DeflateStream dstream = new DeflateStream(output, CompressionLevel.Optimal))
    {
        dstream.Write(data, 0, data.Length);
    }
    return output.ToArray();
}

public byte[] DecompressData(byte[] data)
{
    MemoryStream input = new MemoryStream(data);
    MemoryStream output = new MemoryStream();
    using (DeflateStream dstream = new DeflateStream(input, CompressionMode.Decompress))
    {
        dstream.CopyTo(output);
    }
    return output.ToArray();
}
```
**Encryption**
```C#
using System.Security.Cryptography;

public static string AES_Encrypt(string input, string password)
{
    byte[] clearBytes = System.Text.Encoding.UTF8.GetBytes(input);
    byte[] encryptedData = AES_Encrypt(clearBytes, password);
    return Convert.ToBase64String(encryptedData);
}

public static byte[] AES_Encrypt(byte[] input, string password)
{
    return AES_Encrypt(input, Encoding.UTF8.GetBytes(password));
}

public static byte[] AES_Encrypt(byte[] input, byte[] password)
{
    PasswordDeriveBytes pdb = new PasswordDeriveBytes(password, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
    return AES_Encrypt(input, pdb.GetBytes(32), pdb.GetBytes(16));
}

public static string AES_Decrypt(string input, string password)
{
    byte[] cipherBytes = Convert.FromBase64String(input);
    byte[] decryptedData = AES_Decrypt(cipherBytes, password);
    return System.Text.Encoding.UTF8.GetString(decryptedData);
}

public static byte[] AES_Decrypt(byte[] input, string password)
{
    return AES_Decrypt(input, Encoding.UTF8.GetBytes(password));
}

public static byte[] AES_Decrypt(byte[] input, byte[] password)
{
    PasswordDeriveBytes pdb = new PasswordDeriveBytes(password, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
    return AES_Decrypt(input, pdb.GetBytes(32), pdb.GetBytes(16));
}

static byte[] AES_Encrypt(byte[] clearData, byte[] Key, byte[] IV)
{
    byte[] encryptedData = null;
    using (MemoryStream ms = new MemoryStream())
    {
        using (Rijndael alg = Rijndael.Create())
        {
            alg.Key = Key;
            alg.IV = IV;
            using (CryptoStream cs = new CryptoStream(ms, alg.CreateEncryptor(), CryptoStreamMode.Write))
            {
                cs.Write(clearData, 0, clearData.Length);
                cs.Close();
            }
            encryptedData = ms.ToArray();
        }
    }
    return encryptedData;
}

static byte[] AES_Decrypt(byte[] cipherData, byte[] Key, byte[] IV)
{
    byte[] decryptedData = null;
    using (MemoryStream ms = new MemoryStream())
    {
        using (Rijndael alg = Rijndael.Create())
        {
            alg.Key = Key;
            alg.IV = IV;
            using (CryptoStream cs = new CryptoStream(ms, alg.CreateDecryptor(), CryptoStreamMode.Write))
            {
                cs.Write(cipherData, 0, cipherData.Length);
                cs.Close();
            }
            decryptedData = ms.ToArray();
        }
    }
    return decryptedData;
}
```

**Comment by doItBinary** [comment]
Thank you very much for your response, that definitely should work.
And again, you're doing a great work with this.

**Comment by adriancs2** [comment]
After I have started this project, I have received feedback, bug reports & fixes, code improvement suggestions, patches from kind programmers around the world which makes the library becomes better as time goes. Credits goes to them too :)
Anyway, thanks and you're welcome ;)

**Comment by phil-w** [comment]
I assume you did drop the function as I can't find it in the docs, but the example here is very useful in getting me that sorted - thanks.
