### ISSUE TITLE
Exporting wrong time for large hours values (hhh:mm:ss)

### ISSUE THREAD

**Issue by skogamor** [MySqlBackupNET/MySqlBackup.Net#70]
I have a column that shows the difference between two dates as TIME type. According to the [MySQL reference](https://dev.mysql.com/doc/refman/8.0/en/time.html), TIME can contain large hours values ("hhh: mm: ss").
When exporting the table, all hours > 24 are currently truncated.

**Comment by adriancs2** [comment]
Thanks for the info. Will work on this.

**Comment by adriancs2** [comment]
I have modified. You may test with the following file and see if the problem still exist
[MySqlBackup(NetFramework)_debug_issue_70_v1.zip](https://github.com/MySqlBackupNET/MySqlBackup.Net/files/6065337/MySqlBackup.NetFramework._debug_issue_70_v1.zip)

I have modified the file
/methods/QueryExpress.cs
line 332
change from
```
sb.AppendFormat(dtime.ToString("HH:mm:ss", _dateFormatInfo));
```
to
```
sb.AppendFormat("{0}:{1}:{2}", mdt.Hour, mdt.Minute, mdt.Second);
```

**Comment by skogamor** [comment]
Thanks for the fast respond. Your change looks good, but the result is still the same as before. 
However, I am not sure whether I have integrated the package correctly. So far I had this as a NuGet package. I just replaced the old reference with the MySqlBackup.dll from bin/Release/.

**Comment by skogamor** [comment]
@adriancs2 
Today I finally had some time to debug your code. In my case the object `ob` is of type `TimeSpan`. 
So in _/methods/QueryExpress.cs_ I made some minor changes (line 277ff):
```
else if (ob is TimeSpan)
{
    TimeSpan ts = (TimeSpan)ob;
    int tsTotalHours = (int)ts.TotalHours;
    int tsHours = (tsTotalHours >= 24 || tsTotalHours <= -24) ? tsTotalHours : ts.Hours;

    if (wrapStringWithSingleQuote)
        sb.AppendFormat("'");
    
    sb.AppendFormat(tsHours.ToString().PadLeft(2, '0'));
    sb.AppendFormat(":");
    sb.AppendFormat(ts.Duration().Minutes.ToString().PadLeft(2, '0'));
    sb.AppendFormat(":");
    sb.AppendFormat(ts.Duration().Seconds.ToString().PadLeft(2, '0'));

    if (wrapStringWithSingleQuote)
        sb.AppendFormat("'");
}
```

Added:
```
int tsTotalHours = (int)ts.TotalHours;
int tsHours = (tsTotalHours >= 24 || tsTotalHours <= -24) ? tsTotalHours : ts.Hours;
```

Changed: 
`sb.AppendFormat(ts.Hours.ToString().PadLeft(2, '0'));` to `sb.AppendFormat(ts.Hours.ToString().PadLeft(2, '0'));`

This works fine for me.

**Comment by adriancs2** [comment]
@skogamor 
Nice work!

Here is the second edit, you may try it out:
[MySqlBackup(NetFramework)_debug_issue_70_v2.zip]
(https://github.com/MySqlBackupNET/MySqlBackup.Net/files/6095631/MySqlBackup.NetFramework._debug_issue_70_v2.zip)

Since the `ts.TotalHours` is needed to be cast as anyway, so I applied `(int)ts.TotalHours` directly in the `AppendFormat`:
```
else if (ob is TimeSpan)
{
	TimeSpan ts = (TimeSpan)ob;

	if (wrapStringWithSingleQuote)
		sb.AppendFormat("'");

	sb.AppendFormat(((int)ts.TotalHours).ToString().PadLeft(2, '0'));
	sb.AppendFormat(":");
	sb.AppendFormat(ts.Minutes.ToString().PadLeft(2, '0'));
	sb.AppendFormat(":");
	sb.AppendFormat(ts.Seconds.ToString().PadLeft(2, '0'));

	if (wrapStringWithSingleQuote)
		sb.AppendFormat("'");
}
```

**Comment by skogamor** [comment]
@adriancs2 
Yep, that seems to work too.
I forgot to mention this in my last post .. I recommend adding `ts.Duration().` for minutes and seconds. Otherwise, the `sb` for negative times is something like `'-10:-30:-15'`. 

Do you already know when the next release will appear?

**Comment by skogamor** [comment]
@adriancs2 
Hi, the issue has been fixed with latest new nuget package. 
thanks 👍
