### ISSUE TITLE
problem when update mysql.data after distribution

### ISSUE THREAD

**Issue by aphestark** [MySqlBackupNET/MySqlBackup.Net#74]
version nuget Mysqlbackup 2.3.4
after i update mysql.data from 8.0.23 to 8.0.25 
mysql stop working becaus failed load mysql.data 8.0.23

**Comment by adriancs2** [comment]
I have just released a new version of nuget package to update the dependency of mysql.data to 8.0.25
You may try again

**Comment by aphestark** [comment]
tks. problem solved
