### ISSUE TITLE
MySql.Data.Types.MySqlConversionException

### ISSUE THREAD

**Issue by simrskandou** [MySqlBackupNET/MySqlBackup.Net#75]
MySql.Data.Types.MySqlConversionException
Want to connect to Mariadb

![image](https://user-images.githubusercontent.com/65203325/125555954-e40bdd07-bb81-4476-a8ba-96c88022361d.png)

Thank you for your help

**Comment by adriancs2** [comment]
This can be resolved by adding 1 connection string option: `convertzerodatetime=true`
Example:
```sql
server=127.0.0.1;user=root;pwd=1234;database=test1;convertzerodatetime=true;
```

**Comment by simrskandou** [comment]
Thank you...
