### ISSUE TITLE
Control errors

### ISSUE THREAD

**Issue by ancucu** [MySqlBackupNET/MySqlBackup.Net#8]
how do you verify that the copy or restoration has been successful?
A greeting.

**Comment by adriancs2** [comment]
1 of the simplest way is by comparing the SHA256 hash checksum of the dump file before and after export/import.

Steps:

Reminders: Remember to disable **RecordDumpTime** (ExportInfo.RecordDumpTime=false) during export.

1. Export to 1st dump file.
2. Obtain SHA256 hash checksum of the 1st dump file.
3. Import the 1st dump file into database.
4. Export again into 2nd dump file.
5. Obtain SHA256 hash checksum of the 2nd dump file.
6. Compare both SHA256 hashes from 1st and 2nd dump file.

If both hashes are same, this indicates that the restoration is successful.

**Comment by ancucu** [comment]
Hi.
There is some way to know that it has ended properly.
To add a MessageBox with the result.
A greeting.

**Comment by ancucu** [comment]
Hi.
I already have it resolved.
Thank you.
;))
