### ISSUE TITLE
run in windows is ok, but centOS show error:Could not load file or assembly 'MySqlBackupNet.MySqlConnector, Version=2.3.6.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by CatcherX** [MySqlBackupNET/MySqlBackup.Net#83]
`Could not load file or assembly 'MySqlBackupNet.MySqlConnector, Version=2.3.6.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

my code is :

> backupPath += "\\" + DateTime.Now.ToString("yyyy-MM-dd_HH_mm_ss.sql");
using (MySqlConnection conn = new MySqlConnection(GlobalContext.SystemConfig.DBConnectionString))
{
    using (MySqlCommand cmd = new MySqlCommand())
    {
        using (MySqlBackup mb = new MySqlBackup(cmd))
        {
            cmd.Connection = conn;
            conn.Open();
            mb.ExportToFile(backupPath);
            conn.Close();
        }
    }
}

**Comment by adriancs2** [comment]
MySqlBackupNet.MySqlConnector requires MySqlConnector.NET to run. You may download the .NET Core build of MySqlConnector.NET at: https://www.nuget.org/packages/MySqlConnector/

**Comment by adriancs2** [comment]
In order for the application to be run in CentOS (Linux), the project has to be published in ".NET Core" format.

Starting by creating a .net core linux project:

![01](https://user-images.githubusercontent.com/646615/151096936-47008968-8cd0-4cc8-a506-9c78b300642b.png)

Check the project properties, ensure the project is built with .NET Core framework:

![02](https://user-images.githubusercontent.com/646615/151096957-1ca89eee-a4b3-42dd-b304-9d741c671d48.png)

Install Nuget Package of MySqlBackup.NET (with MySqlConnector):

![03](https://user-images.githubusercontent.com/646615/151096962-a7332012-cbb2-4405-a0b2-35a24b7c92c5.png)

Next, is to publish the project for .NET Core (Linux):

![04](https://user-images.githubusercontent.com/646615/151096977-62c01aa3-51d9-4447-8df4-2734be172f5c.png)

In above example, the Linux compiled binaries are located at:

```
\bin\Release\netcoreapp3.1\publish\linux-x64
```

Copy the DLL at the folder and paste it to your **CentOS**

At the **CentOS**, make sure that you have installed **Dotnet** runtime by following command:
```
sudo dnf install dotnet-sdk-<version>
```
For example:
```
sudo dnf install dotnet-sdk-3.1
sudo dnf install dotnet-sdk-5.0
```
Assume that you have copied your .NET Core DLL files at the following folder:
```
/home/<username>/testapp
```
Then you can test out your app with following command:
```
cd /home/admin/testapp
dotnet ConsoleApp.dll
```
Here is the sample project with source that I have built for .NET Core project for your referrence:
[ConsoleApp2.zip](https://github.com/liukuo362573/YiShaAdmin/files/7938681/ConsoleApp2.zip)

**Comment by adriancs2** [comment]
Above method requires CentOS to install the dotnet runtime by executing the following command:
```
sudo dnf install dotnet-sdk-3.1
sudo dnf install dotnet-sdk-5.0
```
You can also compile the binaries into single "self-contained" binary. With this method, the .NET Core App can be run directly on CentOS (Linux) without installing any dotnet runtime.

Here is the screenshot for publishing the "self-contained" binary:

![05](https://user-images.githubusercontent.com/646615/151179683-ff2ab63f-3fdb-4233-8630-b2808359d76d.png)

Here is the example of how it looks like after publishing, there is only 1 single file:

![06](https://user-images.githubusercontent.com/646615/151179929-cab88c78-f5f7-466e-997d-e6702846e8a5.png)

Copy the compiled binary to CentOS

At the terminal, browse to the folder that contains the self-contained binary, for example:
```
cd /home/admin/testapp
```
Execute the app:
```
./ConsoleApp2
```

**Comment by CatcherX** [comment]
> MySqlBackupNet.MySqlConnector requires MySqlConnector.NET to run. You may download the .NET Core build of MySqlConnector.NET at: https://www.nuget.org/packages/MySqlConnector/

It's working fine now, thank you very much for your patient guidance @adriancs2
