### ISSUE TITLE
Values of generated columns written to the backup file causes exception at restore

### ISSUE THREAD

**Issue by HSyr** [MySqlBackupNET/MySqlBackup.Net#9]
* I have a generated column in a table:
`GeneratedColumn int(11) GENERATED ALWAYS AS (SomeExpression) STORED NOT NULL`

* The backup file from MySqlBackup.NET incorrectly contains:
`INSERT INTO MyTable ( otherColumns, GeneratedColumn ) VALUES ...`

* While the backup created by Export from MySQL workbench does not (correctly) contain the generated column values:
`INSERT INTO MyTable ( otherColumns ) VALUES ...`

* Therefore restore from MySqlBackup.NET file gives:
 MySql.Data.MySqlClient.MySqlException occurred
  HResult=0x80004005
  Message=**The value specified for generated column** 'GeneratedColumn' in table 'MyTable' **is not allowed**.
   StackTrace:
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.MySqlScript.Execute()
   at MySql.Data.MySqlClient.MySqlBackup.Import_AppendLineAndExecute(String line)
   at MySql.Data.MySqlClient.MySqlBackup.Import_ProcessLine(String line)
   at MySql.Data.MySqlClient.MySqlBackup.Import_Start()
   at MySql.Data.MySqlClient.MySqlBackup.ImportFromTextReaderStream(TextReader tr, FileInfo fileInfo)
   at MySql.Data.MySqlClient.MySqlBackup.ImportFromFile(String filePath)

**Comment by adriancs2** [comment]
Hi, I have fixed this bug and committed the source code to the repository. Can try to verify the latest code with your database and see whether the problem still exist or not. Thanks.

**Comment by adriancs2** [comment]
If you wish to test it with the compiled binary, you can download it from here:
http://www.mediafire.com/file/21l2mqdvrapz8ml/MySqlBackup_V2.0.10_debug.zip

**Comment by HSyr** [comment]
Thank you for providing binary as I am not able to compile both old (with the bug) and fixed source files after MySQL.Data from Oracle was updated from NuGet repository to the solution. The VS reports unresolved references for MySQL.Data.

Anyway, using provided binaries I checked the output of Export and it look fine as INSERT INTO data for generated column are missing. I will try the complete Export/Import after you publish the package to the NuGet.

Please let me know when the package is available at NuGet. Thank you.

**Comment by adriancs2** [comment]
No problem. I have upload new NuGet package 2.0.10, you can try it out.
Optionally, you can also obtain the same binaries from the repository here too.
and you should be able to compile the source code now, as I have removed the NuGet package dependencies in the source code.

**Comment by HSyr** [comment]
I updated the NuGet package into my project. The project is a .NET 4.6.1 WinForm app. During a build I got:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0_\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.`

To solve this I had to install a prerelease of MySql.Data v8.0.9-dmr from Oracle into the project. But this forced me to use "MySqlSslMode.None" to connect against development MySQL @ localhost as the localhost does not support SSL (prerelease of MySQL.Data otherwise throws exception that localhost does not support ssl). 

What about to use a released MySql.Data 6.10.4. at MySqlBackup.NET but not the prerelase?

BTW the original issue is fixed. Thanks.

**Comment by adriancs2** [comment]
I have updated the nuget package to include binaries for .NET v4.6.1
You can try again to update the new MySqlBackup nuget package version 2.0.10.1.

_What about to use a released MySql.Data 6.10.4. at MySqlBackup.NET but not the prerelase?_
In the [oracle MySql official release](https://dev.mysql.com/downloads/file/?id=474110), they only include binary for .NET 4.0 and 4.5.

Therefore I have to manually compile .NET 2.0 and .NET 4.6.1 from their source code.

For .NET 4.0 and 4.5 version, the MySql.Data 6.10.4 at MySqlBackup.NET are same as oracle's official release. I copy from their release.

**Comment by adriancs2** [comment]
You're welcome.

**Comment by HSyr** [comment]
After updating your package and returning back to the official MySql.Data release the project did not build without errors.
I had to remove both these packages from the project and then install them back again. Then it compiled OK. Then I also could remove "MySqlSslMode.None".

So now all is OK. I feel like you can close the issue. 

Thanks a lot.

**Comment by adriancs2** [comment]
You're welcome
